---
- name: Tags
  hosts: all
  tasks:
          - name: install vsftpd
            yum:
                    name: vsftpd
                    state: installed
            tags: vsftp

          - name: install php
            yum:
                    name: php
                    state: installed
            tags: php
